
name: bindings typescript

on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  test:
    name: test generated libraries
    runs-on: ubuntu-20.04
    services:
      rpc:
        image: stellar/quickstart:soroban-dev@sha256:8a99332f834ca82e3ac1418143736af59b5288e792d1c4278d6c547c6ed8da3b
        ports:
          - 8000:8000
        env:
          ENABLE_LOGS: true
          NETWORK: standalone
          ENABLE_SOROBAN_RPC: true
        options: >-
          --health-cmd "curl -X POST \"http://localhost:8000/soroban/rpc\""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - run: echo $CARGO_TARGET_DIR
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: rustup update
    - run: cargo build
    - run: rustup target add wasm32-unknown-unknown
    - run: make build-test-wasms
    - run: npm ci && npm run test
      working-directory: cmd/crates/soroban-spec-typescript/ts-tests
